name: "Prepare environment"
description: "Prepares environment"

inputs:
  tarantool-version:
    required: true
    type: string

runs:
  using: "composite"
  steps:
      - name: Install basic tools
        run: |
          apt-get -y update
          apt-get --allow-releaseinfo-change update
          apt-get -y install sudo git curl gcc make cmake unzip \
          zip gawk cpio pkg-config build-essential ninja-build \
          liblz4-dev autoconf automake libtool lsb-release rsync libunwind-dev \
        shell: bash

      # tzdata package, which is tarantool dependency, asks a user for time zone configuration. The
      # step below disables user interaction for this package.
      - name: Set tzdata
        run: |
          ln -fs /usr/share/zoneinfo/Europe/Moscow /etc/localtime
          echo "DEBIAN_FRONTEND=noninteractive" >> $GITHUB_ENV
          echo "TZ=Europe/Moscow" >> $GITHUB_ENV
        shell: bash

      # Workaround for setup tarantool action: disable dpkg filters, so all files will be installed.
      - name: Disable default dpkg excludes
        run: echo "" > /etc/dpkg/dpkg.cfg.d/excludes
        shell: bash

      - name: Install tarantool ${{ inputs.tarantool-version }}
        if: startsWith(inputs.tarantool-version, 'debug') != true
        uses: tarantool/setup-tarantool@v3
        with:
          tarantool-version: '${{ inputs.tarantool-version }}'

      - name: Setup tt
        run: |
          curl -L https://tarantool.io/release/2/installer.sh | sudo bash
          apt install -y tt
          tt version
        shell: bash
