name: Publish

on:
  push:
    branches: [master]
    tags: ['*']

jobs:
  version-check:
    # We need this job to run only on push with tag.
    if: ${{ github.event_name == 'push' && startsWith(github.ref, 'refs/tags/') }}

    runs-on: ubuntu-20.04
    container:
      image: ubuntu:22.04

    steps:
      - name: Check module version
        uses: tarantool/actions/check-module-version@master
        with:
          module-name: 'ddl-ee'

  publish-tag:
    if: startsWith(github.ref, 'refs/tags/')

    needs: version-check

    runs-on: [self-hosted, Linux, x86_64, regular]
    container:
      image: ubuntu:22.04

    steps:
      - uses: actions/checkout@v4

      - name: Prepare env
        uses: ./.github/actions/prepare-env
        with:
          tarantool-version: '2.11'

      # Make a release
      - run: echo TAG=${GITHUB_REF##*/} >> $GITHUB_ENV
      - run: tt rocks new_version --tag ${{ env.TAG }}
      - run: tt rocks install ddl-${{ env.TAG }}-1.rockspec
      - run: tt rocks pack ddl ${{ env.TAG }}
